-- liquibase formatted sql

-- changeset yehorhavryliuk:20250417-1
CREATE TABLE bids
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lot_id    BIGINT         NOT NULL,
    bidder_id BIGINT         NOT NULL,
    amount    NUMERIC(19, 4) NOT NULL,
    placed_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- changeset yehorhavryliuk:20250417-2
ALTER TABLE bids
    ADD CONSTRAINT fk_bid_lot FOREIGN KEY (lot_id) REFERENCES lots (id);

-- changeset yehorhavryliuk:20250417-3
ALTER TABLE bids
    ADD CONSTRAINT fk_bid_user FOREIGN KEY (bidder_id) REFERENCES users (id);

-- changeset yehorhavryliuk:20250417-4
CREATE INDEX idx_bid_lot ON bids (lot_id);
CREATE INDEX idx_bid_bidder ON bids (bidder_id);